In [2]:
import numpy as np

y = np.array([2, 5, 9, 20])
y

array([ 2,  5,  9, 20])

In [3]:
x = np.array([[20, 50, 5], [2, 8, 9], [4, 9, 0]])
x

array([[20, 50,  5],
       [ 2,  8,  9],
       [ 4,  9,  0]])

In [5]:
np.shape(x)

(3, 3)

In [6]:
a = np.array([[3, 4, 5, 6], [0, 7, 9,5], [45, 90, 23, 1], [ 40, 2, 11, 5]])
a

array([[ 3,  4,  5,  6],
       [ 0,  7,  9,  5],
       [45, 90, 23,  1],
       [40,  2, 11,  5]])

In [7]:
np.shape(a)

(4, 4)

In [10]:
mylist = []
x = np.array([2, 4,6])
print(x)

[2 4 6]


In [12]:
a.reshape(16)

array([ 3,  4,  5,  6,  0,  7,  9,  5, 45, 90, 23,  1, 40,  2, 11,  5])

In [20]:
a.reshape(4,4)

array([[ 3,  4,  5,  6],
       [ 0,  7,  9,  5],
       [45, 90, 23,  1],
       [40,  2, 11,  5]])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
man = np.array([2,3, 5])
man

array([2, 3, 5])

In [22]:
(man[0])

2

In [23]:
(man[0:2])

array([2, 3])

In [24]:
(man[-1])

5

In [27]:
mywife = np.array(['man', 'woman', 'girl', 'boy'])
mywife

array(['man', 'woman', 'girl', 'boy'], dtype='<U5')

In [29]:
np.shape(mywife)

(4,)

In [30]:
mywife.reshape(2,2)

array([['man', 'woman'],
       ['girl', 'boy']], dtype='<U5')

In [2]:
import numpy as np

np.zeros([4, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
y = np.array([2, 4, 6])
y

array([2, 4, 6])

In [5]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
x = np.array([[2, 4, 5],[6, 8, 9],[0, 9, 8]])
x

array([[2, 4, 5],
       [6, 8, 9],
       [0, 9, 8]])

In [10]:
x.reshape(3,3)

array([[2, 4, 5],
       [6, 8, 9],
       [0, 9, 8]])

In [12]:
np.shape(x)

(3, 3)

In [13]:
a = np.array([[2, 'man', 4], [9, 6, 7], [3, 4.0, 2], [1, 8, 2.0]] )
a

array([['2', 'man', '4'],
       ['9', '6', '7'],
       ['3', '4.0', '2'],
       ['1', '8', '2.0']], dtype='<U32')

In [14]:
np.shape(a)

(4, 3)

In [15]:
a.reshape(4,3)

array([['2', 'man', '4'],
       ['9', '6', '7'],
       ['3', '4.0', '2'],
       ['1', '8', '2.0']], dtype='<U32')

In [19]:
def add_number(x, y):
    return(x + y)

add_number(4, 10)

14

In [20]:
def subtract(a, b):
    return(a - b)

subtract(18,6)

12

In [22]:
x = 6
if (x > 5):
    print('x is better than 5')
else:
    print('x is less than 5')

x is better than 5


In [23]:
y = [number for number in range(0,200) if number % 2 == 0]
y

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

In [24]:
userDetails = {'name': 'miracle', 'surname': ' edeh', 'age': '24'}
userDetails

{'name': 'miracle', 'surname': ' edeh', 'age': '24'}

In [25]:
userDetails.values()

dict_values(['miracle', ' edeh', '24'])

In [26]:
userDetails.keys()

dict_keys(['name', 'surname', 'age'])

In [27]:
userDetails.items()

dict_items([('name', 'miracle'), ('surname', ' edeh'), ('age', '24')])

In [28]:
for items in userDetails.values():
    print(items)

miracle
 edeh
24
