In [1]:
y = 2
y

2

In [6]:
import pandas as pd

In [7]:
x = pd.Series([2,3,4,5])
x

0    2
1    3
2    4
3    5
dtype: int64

In [8]:
val = [20,5,'man']
x = pd.Series(val)
x

0     20
1      5
2    man
dtype: object

In [12]:
details1 = pd.Series({'name': 'oluchi',
                     'password': 'olu3',
                     'country': 'usa',
                     'age': '25',
                     'sport': 'basketball',
                     'department': 'com si'})

details2 = pd.Series({'name': 'eben',
                     'password': 'eben10',
                     'country': 'nigeria',
                     'age': '32',
                     'sport': 'golf',
                     'department': 'com si'})

details3 = pd.Series({'name': 'esther',
                     'password': 'esther20',
                     'country': 'india',
                     'age': '22',
                     'sport': 'cricket',
                     'department': 'bus admin'})

details4 = pd.Series({'name': 'michael',
                     'password': 'mike02',
                     'country': 'china',
                     'age': '23',
                     'sport': 'takwando',
                     'department': 'mass com'})

details5 = pd.Series({'name': 'clara',
                     'password': 'clara33',
                     'country': 'canada',
                     'age': '30',
                     'sport': 'bassball',
                     'department': 'sales'})

df = pd.DataFrame([details1, details2, details3, details4, details5], index = ['details1', 'details2', 'details3', 'details4', 'details5'])
df


name  password  country age       sport department
details1   oluchi      olu3      usa  25  basketball     com si
details2     eben    eben10  nigeria  32        golf     com si
details3   esther  esther20    india  22     cricket  bus admin
details4  michael    mike02    china  23    takwando   mass com
details5    clara   clara33   canada  30    bassball      sales

In [14]:
df.loc['details1']

name              oluchi
password            olu3
country              usa
age                   25
sport         basketball
department        com si
Name: details1, dtype: object

In [15]:
df.loc['details4']

name           michael
password        mike02
country          china
age                 23
sport         takwando
department    mass com
Name: details4, dtype: object

In [17]:
df.loc['details3'] = 'country'
df

name password  country      age       sport department
details1   oluchi     olu3      usa       25  basketball     com si
details2     eben   eben10  nigeria       32        golf     com si
details3  country  country  country  country     country    country
details4  michael   mike02    china       23    takwando   mass com
details5    clara  clara33   canada       30    bassball      sales

In [20]:
df.T.loc['department']

details1      com si
details2      com si
details3     country
details4    mass com
details5       sales
Name: department, dtype: object

In [21]:
df.T.loc['name']

details1     oluchi
details2       eben
details3    country
details4    michael
details5      clara
Name: name, dtype: object

In [25]:
df.drop(['details2'])

name password  country      age       sport department
details1   oluchi     olu3      usa       25  basketball     com si
details3  country  country  country  country     country    country
details4  michael   mike02    china       23    takwando   mass com
details5    clara  clara33   canada       30    bassball      sales

In [26]:
df.drop(['details3'])

name password  country age       sport department
details1   oluchi     olu3      usa  25  basketball     com si
details2     eben   eben10  nigeria  32        golf     com si
details4  michael   mike02    china  23    takwando   mass com
details5    clara  clara33   canada  30    bassball      sales

In [28]:
name = df['name']
name

details1     oluchi
details2       eben
details3    country
details4    michael
details5      clara
Name: name, dtype: object

In [29]:
password = df['password']
password

details1       olu3
details2     eben10
details3    country
details4     mike02
details5    clara33
Name: password, dtype: object

In [30]:
country = df['country']
country


details1        usa
details2    nigeria
details3    country
details4      china
details5     canada
Name: country, dtype: object

In [31]:
department = df['department']
department

details1      com si
details2      com si
details3     country
details4    mass com
details5       sales
Name: department, dtype: object

In [46]:
import numpy as np


In [48]:
x = np.array([20,3,4])
x

array([20,  3,  4])

In [49]:
man = [1, 2, 4, 8, 0, 22]
x = np.array(man)
x

array([ 1,  2,  4,  8,  0, 22])

In [52]:
sun = np.array([[1,2,3], [3,5,7], [6,7,8], [9,0,4]])
sun

array([[1, 2, 3],
       [3, 5, 7],
       [6, 7, 8],
       [9, 0, 4]])

In [53]:
type(sun)

numpy.ndarray

In [54]:
np.shape(sun)

(4, 3)

In [58]:
sun.reshape(12)

array([1, 2, 3, 3, 5, 7, 6, 7, 8, 9, 0, 4])

In [59]:
sun.reshape(4,3)

array([[1, 2, 3],
       [3, 5, 7],
       [6, 7, 8],
       [9, 0, 4]])

In [60]:
[0]

[0]

In [61]:
sun.mean()

4.583333333333333

In [62]:
sun.argmax()

9

In [63]:
sun.argmin()

10

In [64]:
sun.sum()

55

In [66]:
b = 0
for x in sun:
    b = b + x
    
b

array([19, 14, 22])

In [67]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
x = np.array([2,4,7])
x

array([2, 4, 7])

In [72]:
y = np.array([3,8,9])
y

array([3, 8, 9])

In [73]:
print(x + y)

[ 5 12 16]


In [74]:
print(x * y)

[ 6 32 63]


In [75]:
print(x % y)

[2 4 7]


In [78]:
print(y / x)

[1.5        2.         1.28571429]


In [79]:
print(x - y)

[-1 -4 -2]


In [80]:
userDetails = {'name': 'ada',
              'email': 'ada@gmail.com',
              'age': '20'}
userDetails

{'name': 'ada', 'email': 'ada@gmail.com', 'age': '20'}

In [82]:
userDetails.values()

dict_values(['ada', 'ada@gmail.com', '20'])

In [83]:
userDetails.keys()

dict_keys(['name', 'email', 'age'])

In [84]:
userDetails.items()

dict_items([('name', 'ada'), ('email', 'ada@gmail.com'), ('age', '20')])

In [85]:
for items in userDetails.values():
    print(items)

ada
ada@gmail.com
20


In [86]:
userDetails['name']

'ada'

In [88]:
userDetails['email']

'ada@gmail.com'

In [89]:
sun[2]

array([6, 7, 8])

In [93]:
sun[3], sun[0]

(array([9, 0, 4]), array([1, 2, 3]))

In [94]:
sun

array([[1, 2, 3],
       [3, 5, 7],
       [6, 7, 8],
       [9, 0, 4]])

In [95]:
sun[3, 2]

4

In [97]:
sun[2, 2]

8

In [98]:
sun[0,1]

2