In [2]:
y = "x"
y

'x'

In [3]:
x = [2, 3, 4]
x

[2, 3, 4]

In [4]:
s = [x]*2
s

[[2, 3, 4], [2, 3, 4]]

In [5]:
x[0]

2

In [6]:
x[:2]

[2, 3]

In [7]:
def addnumbers(x,y):
    return(x + y)

addnumbers(10,5)

15

In [19]:
mylist = []
for number in range(0,200):
    if number % 2 == 0:
        mylist.append(number)   
    print(mylist)

[0]
[0]
[0, 2]
[0, 2]
[0, 2, 4]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[0, 2, 4, 6, 8, 10, 

In [21]:
xy = [number for number in range(0,100) if number % 4 == 0]
xy.append(number)
print(xy)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 199]


In [23]:
x = 10
if (x > 5):
    print('x is greater than 5')
else:
    print('x is less than 5')   

x is greater than 5


In [24]:
import numpy as np


In [25]:
x = np.array([2, 3, 5])
x

array([2, 3, 5])

In [26]:
y = np.array([[2, 4, 5, 6],[6, 7, 8, 9],[1, 0, 3, 9]])
y

array([[2, 4, 5, 6],
       [6, 7, 8, 9],
       [1, 0, 3, 9]])

In [31]:
np.shape(y)

(3, 4)

In [33]:
y.reshape(12)

array([2, 4, 5, 6, 6, 7, 8, 9, 1, 0, 3, 9])

In [34]:
y.reshape(4,3)

array([[2, 4, 5],
       [6, 6, 7],
       [8, 9, 1],
       [0, 3, 9]])

In [36]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [38]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [39]:
x = np.array([2, 5, 6])
x

array([2, 5, 6])

In [40]:
y = np.array([1, 7, 8])
y

array([1, 7, 8])

In [41]:
print(x + y)

[ 3 12 14]


In [42]:
print(x - y)

[ 1 -2 -2]


In [43]:
print(x / y)

[2.         0.71428571 0.75      ]


In [44]:
print(x**2)

[ 4 25 36]


In [45]:
print(x * y)

[ 2 35 48]


In [46]:
print([y, y**2])

[array([1, 7, 8]), array([ 1, 49, 64])]


In [47]:
np.array([x, x**2])

array([[ 2,  5,  6],
       [ 4, 25, 36]])

In [48]:
x.T

array([2, 5, 6])

In [49]:
y.T

array([1, 7, 8])

In [50]:
a = np.array([20, 8, 6])
a

array([20,  8,  6])

In [51]:
a.sum()

34

In [53]:
b = 0
for x in a:
    b = b + x
b

34

In [55]:
a.max()

20

In [56]:
a.min()

6

In [57]:
a.mean()

11.333333333333334

In [59]:
a.std()

6.182412330330469

In [60]:
a.argmax()

0

In [61]:
a.argmin()

2

In [64]:
s = np.arange(0,30, 1)/2
s

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [65]:
s[0]

0.0

In [66]:
s[1], s[2], s [4]

(0.5, 1.0, 2.0)

In [67]:
s[1:6]

array([0.5, 1. , 1.5, 2. , 2.5])

In [76]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [78]:
s.reshape([3,10])

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5]])

In [79]:
s[2]

1.0

In [82]:
s[s > 10]

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [83]:
s[s < 10]

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [86]:
import pandas as pd

In [87]:
x = pd.Series([1, 2, 5])
x

0    1
1    2
2    5
dtype: int64

In [88]:
boy = pd.Series(['man', 'boy', 1.0, 5])
boy

0    man
1    boy
2    1.0
3      5
dtype: object

In [89]:
val = pd.Series([2, 5, 8, 90, 6.1])
val

0     2.0
1     5.0
2     8.0
3    90.0
4     6.1
dtype: float64

In [101]:
sports = {'england': 'football',
         'usa': 'basketball',
          'india': 'cricket',
          'scotland': 'golf'}
s = pd.Series(sports)
s

england       football
usa         basketball
india          cricket
scotland          golf
dtype: object

In [95]:
s.index

Index(['england', 'usa', 'india', 'scotland'], dtype='object')

In [102]:
s.iloc[2]

'cricket'

In [103]:
s.iloc[3]

'golf'

In [105]:
s.loc['england']

'football'

In [106]:
s.loc['scotland']

'golf'

In [107]:
len(s)

4

In [109]:
s.loc['nigeria'] = 'okoso'
s

england       football
usa         basketball
india          cricket
scotland          golf
nigeria          okoso
dtype: object

In [110]:
s.loc['bhutan']= 'archery'
s

england       football
usa         basketball
india          cricket
scotland          golf
nigeria          okoso
bhutan         archery
dtype: object

In [123]:
import pandas as pd

details1 =pd.Series({'name': 'jay',
           'surname': 'ajayi',
           'age':  '19',
           'dept': 'com sc',})

details2 = pd.Series({'name': 'eben',
           'surname': 'osuigbo',
           'age':  '32',
           'dept': 'data sci',})

details3 = pd.Series({'name': 'alex',
           'surname': 'ordu',
           'age':  '27',
           'dept': 'buz admin',})
                    
details4 = pd.Series({'name': 'esther',
           'surname': 'micheal',
           'age':  '22',
           'dept': 'business',})

df = pd.DataFrame([details1, details2, details3, details4], index = ['number1','number2','number3','number4'])
df



name  surname age       dept
number1     jay    ajayi  19     com sc
number2    eben  osuigbo  32   data sci
number3    alex     ordu  27  buz admin
number4  esther  micheal  22   business

In [128]:
df.loc['number2']

name           eben
surname     osuigbo
age              32
dept       data sci
Name: number2, dtype: object

In [127]:
df.loc['number1'] = 'name'
df

name  surname   age       dept
number1    name     name  name       name
number2    eben  osuigbo    32   data sci
number3    alex     ordu    27  buz admin
number4  esther  micheal    22   business

In [129]:
df.loc['number4', 'age']

'22'

In [130]:
df.T

number1   number2    number3   number4
name       name      eben       alex    esther
surname    name   osuigbo       ordu   micheal
age        name        32         27        22
dept       name  data sci  buz admin  business