In [1]:
import numpy as np



In [3]:
y = np.array([2, 3, 5])
y

array([2, 3, 5])

In [8]:
x = np.array([[1, 2, 3, 4], [5, 6, 8, 8], [30, 0, 9, 7]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  8,  8],
       [30,  0,  9,  7]])

In [5]:
type(x)

list

In [10]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  8,  8],
       [30,  0,  9,  7]])

In [12]:
a = np.array([[45, 6, 78],[21, 1, 4]])
a

array([[45,  6, 78],
       [21,  1,  4]])

In [13]:
a.reshape(6)

array([45,  6, 78, 21,  1,  4])

In [14]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
def add_number(x, y):
    return(x + y)

add_number(4,7)

11

In [24]:
x = 4
if (x > 5):
    print('x is greater than 5')
else:
    print('x is less than 5')

x is less than 5


In [29]:
mylist = []
for number in range(0,400):
    if number % 2 == 0:
        mylist.append(number)
print(mylist)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398]


In [31]:
x = [number for number in range(0,100) if number % 2 == 0]
print(x)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [32]:
x = (1, 2, 3)
x

(1, 2, 3)

In [33]:
y = [1, 5, 'man', 'guy', 40]
y

[1, 5, 'man', 'guy', 40]

In [34]:
[x] + [y]

[(1, 2, 3), [1, 5, 'man', 'guy', 40]]

In [35]:
[x]*4

[(1, 2, 3), (1, 2, 3), (1, 2, 3), (1, 2, 3)]

In [36]:
(x[0])

1

In [37]:
(x[0:2])

(1, 2)

In [38]:
(x[-1])

3

In [39]:
(y[0:4])

[1, 5, 'man', 'guy']

In [40]:
userDetails = {'name': 'clara', 'surname': 'nwakaeze', 'age': '16'}
userDetails

{'name': 'clara', 'surname': 'nwakaeze', 'age': '16'}

In [41]:
userDetails.keys()

dict_keys(['name', 'surname', 'age'])

In [42]:
userDetails.values()

dict_values(['clara', 'nwakaeze', '16'])

In [43]:
userDetails.items()

dict_items([('name', 'clara'), ('surname', 'nwakaeze'), ('age', '16')])

In [44]:
for items in userDetails.keys():
    print(items)

name
surname
age


In [46]:
for items in userDetails.values():
    print(items)

clara
nwakaeze
16


In [47]:
y = 5
x = 7
a = 9

print(y)
print(x)
print(a)

5
7
9
