In [1]:
y = ('hello world ')
y

'hello world '

In [2]:
x = ('hello ebenezer')
x

'hello ebenezer'

In [3]:
d = ['men', 'women', 13, 44, 0, 2.4]
d

['men', 'women', 13, 44, 0, 2.4]

In [5]:
d.append(20)
d

['men', 'women', 13, 44, 0, 2.4, 20, 20]

In [6]:
[d]*4

[['men', 'women', 13, 44, 0, 2.4, 20, 20],
 ['men', 'women', 13, 44, 0, 2.4, 20, 20],
 ['men', 'women', 13, 44, 0, 2.4, 20, 20],
 ['men', 'women', 13, 44, 0, 2.4, 20, 20]]

In [7]:
[d] + [d]

[['men', 'women', 13, 44, 0, 2.4, 20, 20],
 ['men', 'women', 13, 44, 0, 2.4, 20, 20]]

In [8]:
(d[2])

13

In [9]:
(d[0:4])

['men', 'women', 13, 44]

In [10]:
mylist = []
for number in range(0,200):
    if number % 2 == 0:
        mylist.append(number)
        print(mylist)

[0]
[0, 2]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34

In [12]:
x = 10
if (x > 4):
    print('x is greater than 4')
else:
        print('x is less than')

x is greater than 4


In [18]:
userDetails = {'name': 'precious', 'surname': 'pere'}
print(userDetails)

{'name': 'precious', 'surname': 'pere'}


In [19]:
userDetails.values()

dict_values(['precious', 'pere'])

In [20]:
userDetails.keys()

dict_keys(['name', 'surname'])

In [21]:
userDetails.items()

dict_items([('name', 'precious'), ('surname', 'pere')])

In [22]:
for items in userDetails.keys():
    print(items)

name
surname


In [23]:
def add_number(x,y):
    return(x + y)

add_number(4,9)

13

In [24]:
def subtraction(x,y):
    return(x - y)

subtraction(10,3)

7

In [26]:
import numpy as np
 
y = np.array([2, 4,5])
y

array([2, 4, 5])

In [27]:
x = np.array([[20, 5, 8], [4, 8, 9], [6, 2, 1]])
x

array([[20,  5,  8],
       [ 4,  8,  9],
       [ 6,  2,  1]])

In [28]:
type(x)

numpy.ndarray

In [30]:
x.reshape(9)

array([20,  5,  8,  4,  8,  9,  6,  2,  1])

In [31]:
x.reshape(3,3)

array([[20,  5,  8],
       [ 4,  8,  9],
       [ 6,  2,  1]])

In [38]:
man =np.array([[20, 22, 'mary'], [0, 8, 9], [22, 40, 'sin'], [2.0, 44, 7]])
man

array([['20', '22', 'mary'],
       ['0', '8', '9'],
       ['22', '40', 'sin'],
       ['2.0', '44', '7']], dtype='<U32')

In [39]:
man.reshape([4,3])

array([['20', '22', 'mary'],
       ['0', '8', '9'],
       ['22', '40', 'sin'],
       ['2.0', '44', '7']], dtype='<U32')

In [40]:
np.shape(man)

(4, 3)

In [41]:
np.ones(3)

array([1., 1., 1.])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [44]:
y = [number for number in range(2,100) if number % 2 == 0]
print(y)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [47]:
y = sophia
if myname is(y < sophia):
    print('my name is sophia')
else:
     print('my name is not sophia')

NameError: name 'sophia' is not defined