In [1]:
#  NUMPY IS ALSO KNOWN AS NUMERICAL PHYTON
#     IT IS AN OPEN SOURCE PHYTON LIBRARY WHICH STANDS AS NUMERICAL PHYTON
    
#      THERE ARE 3 MAJOR ALLOCATIONS OF THIS NUMERICAL PHYTON.
        
#         1. MATRICES: IT IS USED FOR THE CREATION OF ARRAYS AND OTHER OPERATIONS
#         2. LINEAR ALGEBRA: PHYTON HAS INBUILT FUNCTIONS TO HANDLE MATHEMATICAL OPERATION CONCERNING LINEAR OPERATION
#         3. FOURIER TRANSFORM: IT HAS INBUILT FUNCTION THAT SUPPORTS THE TRANSFORMATION OF A FUNCTION OF TIME TO 
#             FUNCTION OF FREQUENCY.


In [2]:
# NUMERICAL PHYTON PROGRAMMING (NUMPY)
#  IN OTHER TO USE ANY PHYTON LIBRARY IT MUST BE IMPORTED.
#          TO IMPORT A NUMPY WE USE :

import numpy as np


In [6]:
#     CREATING ARRAYS
y = np.array([1, 3, 10])
y

array([ 1,  3, 10])

In [7]:
mylist = [1, 20, 5]
x = np.array(mylist)
x

array([ 1, 20,  5])

In [ ]:
#  SINGLE DIMENTIONAL ARRAYS ARE CALLED VECTORS

In [9]:
# MULTIDIMENTIONAL ARRAYS

y = np.array([[2, 5, 7],[20,55,40]])
y

array([[ 2,  5,  7],
       [20, 55, 40]])

In [11]:
mylist = np.array([[20, 50,40],[30, 4, 9], [2, 5, 10]])
mylist

array([[20, 50, 40],
       [30,  4,  9],
       [ 2,  5, 10]])

In [14]:
eben = np.array([['amaka', 'esther', 'jane']])
eben

array([['amaka', 'esther', 'jane']], dtype='<U6')

In [15]:
np.shape(mylist)

(3, 3)

In [5]:
 import numpy as np
    
x = np.array([[1,22, 4, 7], [2, 6, 9, 0], [3, 5,4, 76]])
x

array([[ 1, 22,  4,  7],
       [ 2,  6,  9,  0],
       [ 3,  5,  4, 76]])

In [7]:
c = np.array([[20,80,45], [21, 10, 5],[40, 55,23], [70, 24, 84]])
c

array([[20, 80, 45],
       [21, 10,  5],
       [40, 55, 23],
       [70, 24, 84]])

In [11]:
p = np.arange(0, 40, 2)  ##start by 0, count by 2 numbers and stop before 40
p

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [13]:
v = np.arange(0, 90, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [23]:
np.shape(v)

(30,)

In [15]:
 # THE . SHAPE METHOD IS USED TO DETERMINE THE SHAPE OF THE ARRAY
np.shape(c)

(20,)

In [14]:
c = np.arange(0, 100, 5) #start by 0 and count by 5 numbers and stop before 100
c

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [18]:
np.shape(c)

(20,)

In [16]:
np.shape(v)

(30,)

In [17]:
# THE .RESHAPE METHODE IS USED TO RESHAPE AN ALREADY GIVING ARRAY E.G

p.reshape(4, 5) # THIS HAS RESHAPED THE P VECTOR ARRAY INTO A 4 BY 5 DIMENTIONAL ARRAY

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [22]:
c.reshape(2, 10)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [28]:
v.reshape(3, 10)

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42, 45, 48, 51, 54, 57],
       [60, 63, 66, 69, 72, 75, 78, 81, 84, 87]])

In [30]:
 # .ONES ARRAY TYPE RETUNS AN ARRAY OF A GIVING SHAPE BUT ONLY WITH THE FIGURE 1
    
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# ZERO RETURNS A GIVING SHAPE OF A NEW ARRAY FILLED WITH 0

np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
# THE .EYE METHOD RETURNS A 2-D ARRAY WITH ONES ON THE DIAGONAL AND ZEROS EVERYWHERE

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])