In [5]:
import numpy as np
x = np.array([1,2,4])
x

array([1, 2, 4])

In [6]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [7]:
# USE +, -, *, %, / TO PERFORM ELEMENT WISE ADDITION, SUBTRACTION, AND POWER.

print(x)
print(y)

[1 2 4]
[4 5 6]


In [9]:
print(x + y) # elementwise addition [1, 2, 4] + [4, 5, 6] = [5, 7, 10]
print(x - y) # element wise subtraction [1, 2, 4] - [4, 5,6] = [-3, -3, -2]

[ 5  7 10]
[-3 -3 -2]


In [10]:
print(x * y) # element wise multiplication
print(x / y) # element division

[ 4 10 24]
[0.25       0.4        0.66666667]


In [11]:
print(x ** 2) # element wise raise to power

[ 1  4 16]


In [12]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [13]:
z.T  # THIS FUNCTION IS USED TO CHANGE THE SHAPE OR ARRANGEMENT OF AN ARRAY.

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [14]:
 # MATHS FUNCTION
#     NUMPY HAS MANY BUILT IN MATHS FUNCTIONS THAT CAN BE PRFORMED BY ARRAYS

a = np.array([-2, 3, 7, 9,10])
a

array([-2,  3,  7,  9, 10])

In [15]:
# THE .SUM METHOD IS USED TO SUM ALL THE VALUES IN AN ARRAY TOGETHER E.G

a.sum()

27

In [16]:
b = 0              # B IS EQUAL TO ZERO
for x in a:          # X REPRESENTS EACH VALUE IN A ARRAY ABOVE
    b = b + x        # B IS EQUAL 0 + THE FIRST VALUE IN A WHICH IS -2, WHICH IS = -2
                   # THEN THE VALUE OF B CHANGES TO -2 INSTEAD OF 0 AND SO ON.
b

27

In [17]:
 # . MAX IS USED TO PRINT OUT THE MAXIMUM NUMBER IN AN ARRAY E.G
    
a.max()

10

In [18]:
a.min()      # .MIN IS USED TO PRINT OUT THE MINIMUM NUMBER IN AN ARRAY

-2

In [19]:
a.mean()      # .MEAN IS USED TO PRINT OUT THE MEAN IN AM ARRAY

5.4

In [20]:
a.std()        # .STD IS USED TO PRINT OUT THE STANDARD DIVISION OF EACH NUMBER IN AN ARRAY

4.409081537009721

In [21]:
# ARGMAX AND ARGMIN IS USED TO RETURN THE INDEX OF THE MAXIMUM AND MINIMUM VALUES IN THE ARRAY

# NOTE: IN INDEXING OUR VALUES STARTS FROM 0 SO

a.argmax()

4

In [22]:
a.argmin()

0

In [23]:
# INDEXING / SLICING

s = np.arange(0, 30,1)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [24]:
s[0], s[5], s[-3]

(0, 25, 729)

In [25]:
s[1:8]

array([ 1,  4,  9, 16, 25, 36, 49])

In [29]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
# ROW ARE HORIZONTAL, COLUMS ARE VERTICAL

r[2,2]   # THIS MEANS THE SECOND INDEX OF THE ROW AND THE SECOND INDEX OF THE COLUME


14

In [32]:
r[2]

array([12, 13, 14, 15, 16, 17])

In [33]:
r[0]

array([0, 1, 2, 3, 4, 5])

In [34]:
r[2,4]

16

In [35]:
r[3]  # THIS IS PRINTING OUT THE 3 ROW 

array([18, 19, 20, 21, 22, 23])

In [36]:
r[3, 3:6]   # THIS IS PRINTING OUT THE 3RD ROW AND THE INDEX NUMBER RANGING FROM 3-5

array([21, 22, 23])

In [37]:
r[r < 30]    # THIS WILL PRINT OUT ARRAY NUMBERS LESS THAN 30

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
r[r > 30]   # THIS IS GOING TO PRINT OUT THE ARRAY NUMBERS WHICH IS GREATER THAN 30

array([31, 32, 33, 34, 35])

In [39]:
r[r > 20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])