In [1]:
x = 7
y = 10
print(x + y)

17


In [3]:
mylist = []
for number in range(0,200):
    if number % 2 == 0:
        mylist.append(number)
        print(mylist)
    

[0]
[0, 2]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34

In [5]:
eben = []
for number in range(20,500):
    if number % 3 == 0:
        eben.append(number)
        print(eben)

[21]
[21, 24]
[21, 24, 27]
[21, 24, 27, 30]
[21, 24, 27, 30, 33]
[21, 24, 27, 30, 33, 36]
[21, 24, 27, 30, 33, 36, 39]
[21, 24, 27, 30, 33, 36, 39, 42]
[21, 24, 27, 30, 33, 36, 39, 42, 45]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81]
[21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60

In [8]:
man = [number for number in range(10,300) if number % 4 == 0]
print(man)

[12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200, 204, 208, 212, 216, 220, 224, 228, 232, 236, 240, 244, 248, 252, 256, 260, 264, 268, 272, 276, 280, 284, 288, 292, 296]


In [9]:
def add_number(x,y):
    return(x + y)

add_number(20,44)

64

In [10]:
def subtract_number(x,y):
    return(x-y)

subtract_number(60,2)

58

In [13]:
x = 10
if (x > 40):
    print('x is greater than 40')
else:
    print('x is less than 40')

x is less than 40


In [14]:
y = 26
if (y < 4):
    print('y is less than 4')
else:
    print('y is greater than 4')

y is greater than 4


In [15]:
x = ([2, 4, 5, 7])
x

[2, 4, 5, 7]

In [20]:
(x[0])

2

In [19]:
(x[0:2])

[2, 4]

In [21]:
(x[-3])

4

In [22]:
a = ['man', 2, 40, 2.7]
a

['man', 2, 40, 2.7]

In [25]:
(a[0])

'man'

In [27]:
print(a[1])
print(a[2])
print(a[3])

2
40
2.7


In [29]:
a.append(number)
a


['man', 2, 40, 2.7, 499, 499]

In [34]:
a.append(56)
a

['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love', 56]

In [33]:
a.append('love')
a

['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love']

In [35]:
[a]*4

[['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love', 56],
 ['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love', 56],
 ['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love', 56],
 ['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love', 56]]

In [37]:
b = [68, 1.0, 3]
b

[68, 1.0, 3]

In [38]:
[a] + [b]

[['man', 2, 40, 2.7, 499, 499, 56, 'love', 'love', 56], [68, 1.0, 3]]

In [41]:
[b]*2

[[68, 1.0, 3], [68, 1.0, 3]]

In [42]:
print(b[0:4])

[68, 1.0, 3]


In [44]:
userDetails = {'name': 'ebenezer', 'surname': 'osuigbo', 'sex': 'male'}
userDetails

{'name': 'ebenezer', 'surname': 'osuigbo', 'sex': 'male'}

In [45]:
userDetails.values()

dict_values(['ebenezer', 'osuigbo', 'male'])

In [46]:
userDetails.keys()

dict_keys(['name', 'surname', 'sex'])

In [47]:
userDetails.items()

dict_items([('name', 'ebenezer'), ('surname', 'osuigbo'), ('sex', 'male')])

In [51]:
for items in userDetails.values():
    print(items)

ebenezer
osuigbo
male


In [52]:
for items in userDetails.keys():
    print(items)

name
surname
sex


In [53]:
import numpy as np

In [54]:
y = np.array([2, 3, 5,])
y

array([2, 3, 5])

In [55]:
x = np.array([40, 7, 6])
x

array([40,  7,  6])

In [56]:
item = [1, 3, 4]
np.array(item)
print(item)

[1, 3, 4]


In [59]:
y = np.array([[20, 6, 9, 8], [4, 0, 5, 3]])
print(y)

[[20  6  9  8]
 [ 4  0  5  3]]


In [60]:
x = np.array([[22, 33, 4, 5], [8, 7, 9, 0], [ 44, 6, 77, 87], [32, 43, 54, 2]])
x

array([[22, 33,  4,  5],
       [ 8,  7,  9,  0],
       [44,  6, 77, 87],
       [32, 43, 54,  2]])

In [61]:
type(x)

numpy.ndarray

In [62]:
np.shape(x)

(4, 4)

In [63]:
np.shape(y)

(2, 4)

In [65]:
p = np.arange(0, 50 ,2)
p


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [75]:
b = np.arange(0, 80, 2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78])

In [67]:
np.shape(b)

(29,)

In [68]:
np.shape(x)

(4, 4)

In [72]:
p.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [73]:
p.reshape(25)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [77]:
y = 40 / 5
y

8.0

In [78]:
b.reshape(5,8)

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58, 60, 62],
       [64, 66, 68, 70, 72, 74, 76, 78]])

In [79]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])